### ISSUE TITLE
Error with hypermorphic + webpack?

### ISSUE THREAD

**Issue by marcoscaceres** [WebReflection/hypermorphic#10]
Hi @WebReflection! 

Was trying to import hyperHTML into a new project using webpack, but it kept coming up with an empty object ... so ended  at hypermorphic.. 

But now getting strange error:

```
ERROR in ./node_modules/uglify-js/tools/node.js
Module not found: Error: Can't resolve 'fs' in '/Users/marcos/Dropbox/For prototype/prototype/node_modules/uglify-js/tools'
 @ ./node_modules/uglify-js/tools/node.js 1:9-22
 @ ./node_modules/viperhtml/index.js
 @ ./node_modules/hypermorphic/index.js
 @ ./src/InventoryTable.js
 @ ./src/index.js
 @ multi (webpack)-dev-server/client?https://localhost:8080 ./src/index.js
```

Seems as if Webpack is bundling  uglify-js because hypermorphic depends on it?  Expains why "fs" can't be found :) 

The "./src/InventoryTable.js" just does:
 
```JS
import { bind, wire } from "hypermorphic";
```

Bit lost... any ideas? Also, any ideas why hyperHTML won't just import without requiring hypermorphic?  

This is the webpack config:

```JS
module.exports = {
  entry: ["./src/index.js"],
  devtool: "source-map",
  mode: "development",
  output: {
    path: __dirname,
    filename: "./build/bundle.js",
  },
  resolve: {
    extensions: [".js"],
  },
  module: {
    rules: [
      {
        test: /\.css$/,
        use: ["style-loader", "css-loader"],
      },
    ],
  },
};
```

**Comment by WebReflection** [comment]
Have you tried to import from "hyperhtml/esm" instead?

If that doesn't work, can you try to import from "hyperhtml/cjs" ?

**Comment by marcoscaceres** [comment]
I haven't tried, no (but thanks in advance). js modules, so broken 😢 Will probably close in 1 min.

**Comment by marcoscaceres** [comment]
hyperhtml/cjs worked! thanks!

**Comment by WebReflection** [comment]
> js modules, so broken 😢 

to be honest, webpack here is broken too. It uses the `browser` field instead of the `main` one and ignores the `module` field.

I've mentioned this to @TheLarkInn various times but I have no idea what's the state there. Other bundlers have no issues with hyperhtml, the browser field is used in http://unpkg.com/ too so I hope web pack will fix that mistake ASAP.

**Comment by WebReflection** [comment]
P.S. the examples folder in this repo also offers a working web pack configuration:
https://github.com/WebReflection/hypermorphic/blob/master/example/webpack/webpack.config.js

```js
module.exports = {
  mode: 'production',
  entry: './client/index.js',
  resolve: {
    alias: {
      // hyperhtml/cjs is returned by hypermorphic
      // so that aliasing viperhtml as hyperhtml/cjs
      // will basically nullify viperhtml require
      'viperhtml': 'hyperhtml/cjs'
    }
  }
};
```

that would make web pack ignore `viperhtml` and `fs` and all its requires 😉

**Comment by marcoscaceres** [comment]
Thanks! sorry I missed that.

**Comment by WebReflection** [comment]
no need to be sorry, as result I've added a note in the README since it was written nowhere:
https://github.com/WebReflection/hypermorphic#bundlers

Thank you!
